---
- name: Add config
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    mode: '0644'

- name: Add static key to client
  copy:
    dest: /etc/openvpn/static.key
    content: "{{ hostvars['server'].static_key.stdout }}"
    mode: '0644'

- name: Start OpenVPN service
  systemd:
    name: openvpn@server
    enabled: true
    state: started
