---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt     
platforms:
  - name: instance
    box: centos/7
    memory: 512
    cpus: 1  
provisioner:
  name: ansible 
  inventory: 
    group_vars:
      all:
        listen_port: 80
lint: |
  set -e
  yamllint .
  ANSIBLE_ROLES_PATH=../ ansible-lint
  flake8
verifier:
  name: testinfra
