version: '3.9'

services:
  nginx:
    image: kovtalex/nginx:v2
    ports:
      - 8080:80
    volumes:
      - php:/php
    networks:
      - hw14
  php:
    image: kovtalex/php-fpm:v1
    volumes:
      - php:/php    
    networks:
      - hw14

volumes:
  php:

networks:
  hw14:
