{
 "title": "Node Exporter - Alexey Kovtunovich",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU%",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\"}[5m]))*100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\"}[5m]))*100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))*100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Avaliable" },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second eth0",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth0\"}[5m])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth0\"}[5m])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" },
    {
     "expr": "sum(count(node_cpu_seconds_total{mode='system'}) by (cpu))",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[5m])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used%",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}