---
- hosts: all
  become: true
  tasks:

  # echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
  - name: disable default route
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no
    when: (ansible_hostname == "centralRouter") or (ansible_hostname == "centralServer")

  - name: Setup bonding on inetRouter
    block:
      - name: Setup bond0
        template:
          src: inetRouter_bond.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-bond0
          owner: root
          group: root
          mode: 0644
      - name: Setup eth1
        template:
          src: inetRouter_eth1.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-eth1
          owner: root
          group: root
          mode: 0644
      - name: Setup eth2
        template:
          src: inetRouter_eth2.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-eth2
          owner: root
          group: root
          mode: 0644
      - name: Restart network
        service:
          name: network
          state: restarted
          enabled: true
    when: (ansible_hostname == "inetRouter")

  - name: Setup bonding on centralRouter
    block:
      - name: Setup bond0
        template:
          src: centralRouter_bond.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-bond0
          owner: root
          group: root
          mode: 0644
      - name: Setup eth1
        template:
          src: centralRouter_eth1.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-eth1
          owner: root
          group: root
          mode: 0644
      - name: Setup eth2
        template:
          src: centralRouter_eth3.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-eth3
          owner: root
          group: root
          mode: 0644
      - name: Restart network
        service:
          name: network
          state: restarted
          enabled: true
    when: (ansible_hostname == "centralRouter")

  - name: install traceroute to Debian or Ubuntu
    apt:
      name:
        - traceroute
      state: present
      update_cache: true
    when: (ansible_os_family == "Debian") or (ansible_os_family == "Ubuntu")

  - name: install traceroute to CentOS
    yum:
      name:
        - traceroute
      state: present
      update_cache: true
    when: (ansible_os_family == "CentOS")

  - name: Set up NAT on inetRouter
    block:
      - name: install iptables
        yum:
          name:
            - iptables
            - iptables-services
          state: present
          update_cache: true

      - name: copy iptables config
        template:
          src: iptables
          dest: /etc/sysconfig/iptables
          owner: root
          group: root
          mode: 0600

      - name: start and enable iptables service
        service:
          name: iptables
          state: restarted
          enabled: true
    when: (ansible_hostname == "inetRouter")

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
    when: "'routers' in group_names"

  - name: set up route on inetRouter eth1
    template:
      src: inetRouter_route_eth1.j2
      dest: /etc/sysconfig/network-scripts/route-eth1
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "inetRouter")

  # echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
  # - name: add default gateway for centralRouter
  #   lineinfile:
  #     dest: /etc/sysconfig/network-scripts/ifcfg-eth1
  #     line: GATEWAY=192.168.255.1
  #   when: (ansible_hostname == "centralRouter")

  # echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
  - name: add default gateway for centralServer
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.0.1
    when: (ansible_hostname == "centralServer")

  - name: set up route on centralRouter eth5
    template:
      src: centralRouter_route_eth5.j2
      dest: /etc/sysconfig/network-scripts/route-eth5
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "centralRouter")

  - name: set up route on centralRouter eth6
    template:
      src: centralRouter_route_eth6.j2
      dest: /etc/sysconfig/network-scripts/route-eth6
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "centralRouter")

  - name: set up route on office1Router
    template:
      src: office1Router_route.j2
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "office1Router")

  - name: set up route on office1Server
    template:
      src: office1Server_route.j2
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "office1Server")

  - name: set up route on testClient1
    template:
      src: testClient1_route.j2
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "testClient1")

  - name: set up route on testClient2
    template:
      src: testClient2_route.j2
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "testClient2")

  - name: set up route on testServer1
    template:
      src: testServer1_route.j2
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "testServer1")

  - name: set up route on testServer2
    template:
      src: testServer2_route.j2
      dest: /etc/netplan/50-vagrant.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "testServer2")

  - name: set up route on office2Router
    template:
      src: office2Router_route.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "office2Router")

  - name: set up route on office2Server
    template:
      src: office2Server_route.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "office2Server")

  - name: reboot hosts
    block:
    - shell: systemctl reboot
      async: 300
      poll: 0
      ignore_errors: true

    - name: wait for system to come back online
      wait_for_connection:
        delay: 60
        timeout: 300
