# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_EXPERIMENTAL'] = "disks"

Vagrant.configure("2") do |config|

  config.vm.box = 'centos/7'
  config.vm.box_version = '1804.02'

  # config.vm.synced_folder ".", "/vagrant"

  config.vm.define "hw7star" do |box|
  
    box.vm.host_name = "hw7star"
    box.vm.disk :disk, size: "40GB", name: "disk1"

    box.vm.provider "virtualbox" do |vb|
      vb.cpus = 2      
      vb.memory = 1024
    end

    box.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
      yum install -y lvm2 xfsdump
    SHELL
  end  
end
